#!/bin/bash 

export LC_CTYPE=en_GB.UTF-8
export LC_ALL="en_GB.utf-8"
export PATH="/home/tom/miniconda3/bin:/home/tom/.nix-profile/bin:/usr/local/bin:/usr/bin:/bin:/home/tom/data/apps/rerun:/home/tom/data/apps/liteide/bin"
for filename in /home/tom/bins/*/; do
  export PATH=$filename:$PATH
done

[ -r $HOME/rerun/etc/bash_completion.sh ] && source $HOME/rerun/etc/bash_completion.sh
export LD_LIBRARY_PATH=:/etc/ld.so.conf.d/vte.conf$LD_LIBRARY_PATH
export KITTY_DIR=/home/data/apps/kitty

NIX_LINK=/home/ivan/.nix-profile
export LD_LIBRARY_PATH="$NIX_LINK"/lib
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
