


### Added by Zplugin's installer
source '/home/tom/.zplugin/bin/zplugin.zsh'
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk


zplugin load urbainvaes/fzf-marks
zplugin load oknowton/zsh-dwim 
zplugin load MikeDacre/cdbk
#zplugin load
zplugin load joepvd/zsh-hints
zplugin load molovo/lumberjack
zplugin load oz/safe-paste
zplugin ice from"gh-r" as"program"; zplugin load junegunn/fzf-bin
zplugin load mfaerevaag/wd
zplugin load seletskiy/zsh-fuzzy-search-and-edit
zplugin load supercrabtree/k
zplugin load tarrasch/zsh-bd
zplugin load willghatch/zsh-hooks
zplugin load zsh-users/zsh-syntax-highlighting
zplugin load bhilburn/powerlevel9k
zplugin load zsh-users/zsh-autosuggestions
zplugin load zsh-users/zsh-completions
zplugin load zsh-users/zsh-history-substring-search
zplugin load mafredri/zsh-async
zplugin load arzzen/calc.plugin.zsh
zplugin load b4b4r07/enhancd
zplugin load changyuheng/zsh-interactive-cd
zplugin load djui/alias-tips
zplugin load hlissner/zsh-autopair
zplugin load jocelynmallon/zshmarks
zplugin load zdharma/zredis
: zplugin load zdharma/zconvey
zplugin load zdharma/history-search-multi-word
zplugin load zdharma/fast-syntax-highlighting
zplugin load mollifier/cd-gitroot
zplugin load /bric3/nice-exit-code
zplugin load mollifier/anyframe
zplugin light zdharma/zui
zplugin ice wait'[[ -n ${ZLAST_COMMANDS[(r)cras*]} ]]'
zplugin light zdharma/zplugin-crasis
CRASIS_THEME="zdharma-256" CRASIS_LAYOUT="contract"

for file in /home/tom/Share/Config/dotfiles/chroot/dots/shells/zsh/source/*.zsh; do
    source "$file"
done
source /home/tom/Share/Config/dotfiles/chroot/dots/shells/zsh/zaw/zaw.zsh
pathAppend /home/tom/.local/bin
pathAppend /home/tom/bin
pathAppend /home/tom/bin
/home/tom/.local/lib/node/node-9.8.0/bin/
wd() {
  . /home/tom/bin/wd/wd.sh
}
