-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["managed"] = {
            [1] = {
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["level"] = 0,
                        ["split_tree"] = {
                            ["dir"] = "vertical",
                            ["tls"] = 1065,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["switchto"] = true,
                                            ["level"] = 0,
                                            ["geom"] = {
                                                ["h"] = 1043,
                                                ["w"] = 1918,
                                                ["x"] = 1,
                                                ["y"] = 21,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["level"] = 1,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["h"] = 1043,
                                                        ["w"] = 1918,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 1,
                                                    ["windowid"] = 18874378,
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["name"] = "WGroupCW",
                                            ["type"] = "WGroupCW",
                                        },
                                    },
                                    ["name"] = "WFrame<1>",
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1080,
                            ["w"] = 1920,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["name"] = "WTiling",
                        ["type"] = "WTiling",
                    },
                },
                ["geom"] = {
                    ["h"] = 1080,
                    ["w"] = 1920,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                    [2] = "DP2",
                },
                ["level"] = 0,
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["name"] = "WGroupWS",
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["pseudomodal"] = true,
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["level"] = 1,
                ["unnumbered"] = true,
                ["managed"] = {
                    [1] = {
                        ["managed"] = {
                        },
                        ["bottom"] = true,
                        ["mode"] = 0,
                        ["geom"] = {
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 640,
                            ["y"] = 300,
                        },
                        ["level"] = 1025,
                        ["sizepolicy"] = "free_glue",
                        ["name"] = "*scratchpad*",
                        ["type"] = "WFrame",
                    },
                },
                ["geom"] = {
                    ["h"] = 1080,
                    ["w"] = 1920,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                },
                ["name"] = "*scratchws*",
            },
        },
        ["name"] = "WScreen",
        ["type"] = "WScreen",
    },
}

