#!/bin/bash 
export df=/core
export LC_CTYPE=en_GB.UTF-8
export LC_ALL="en_GB.utf-8"
export PATH="/home/tom/miniconda3/bin:/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/go/bin:/home/tom/go/bin"
for filename in /home/tom/bins/*/; do
  export PATH=$filename:$PATH
done
export QUICKNOTEFILE="$HOME/Projects/organisation/dump/quicknotes"
