#!/bin/bash


kill $(ps aux | grep 'xcape -e Shift_L Control_L comma Control_L Control_L grave Alt_L Control_L semicolon Super_L Super_L 1 Alt_R Alt_L comma Shift_R Alt_L grave Control_R Alt_L semicolon' | awk '{print $2}')
xcape -e 'Shift_L=Control_L|comma;Control_L=Control_L|grave;Alt_L=Control_L|semicolon;Super_L=Super_L|1;ISO_Level3_Shift=Alt_L|comma;Shift_R=Alt_L|grave;Control_R=Alt_L|semicolon'









