 bindkey  '^A'           zaw-aliases
 bindkey  '^L'      zaw-applications
 bindkey  '^B'          zaw-bookmark
 bindkey  '^O'    zaw-command-output
 bindkey  '^C'          zaw-commands
 #bindkey  '^R'              zaw-fasd
 #bindkey  '^R'  zaw-fasd-directories
 #bindkey  '^R'        zaw-fasd-files
 #bindkey  '^R'         zaw-functions
 #bindkey  '^R'      zaw-git-branches
 #bindkey  '^R'         zaw-git-files
 #bindkey  '^R'  zaw-git-files-legacy
 #bindkey  '^R'           zaw-git-log
 #bindkey  '^R'  zaw-git-recent-all-branches
 #bindkey  '^R'  zaw-git-recent-branches
 #bindkey  '^R'        zaw-git-reflog
 #bindkey  '^R'        zaw-git-status
 #bindkey  '^R'           zaw-history
 bindkey  '^S'            zaw-locate
 bindkey  '^F'         zaw-open-file
 #bindkey  '^R'           zaw-perldoc
 bindkey  '^P'           zaw-process
 bindkey  '^G'          zaw-programs
 #bindkey  '^R'           zaw-screens
 bindkey  '^Z'          zaw-searcher
 #bindkey  '^R'         zaw-ssh-hosts
 #bindkey  '^R'              zaw-tmux
 #bindkey  '^R'           zaw-widgets