#!/bin/bash
df=/core
SETUP="$df/setup"
TASKS="$SETUP/scripts/tasks"
LISTS="$SETUP/setup/scripts/package_lists"
TASKS="$SETUP/setup/scripts/tasks"

# for f in $TASKS; do source $f; done
# for f in $PACKAGELISTS; do source $f; done
. $SETUP/scripts/fedora/kde/tasks/install_functions

post_install_function() {



install_download_tools
install_build_tools
sudo chown -R tom:tom /home/tom/.cache

install_archive_tools
install_prog_langs
install_automation_tools
install_gnome-pie
install_bleachbit
install_keepass2
install_kate
install_gnome_extras
sudo chown -R tom:tom /home/tom/.cache

#nemo_latest_install
jumpapp_install
fish_install
conda_install
sudo chown -R tom:tom /home/tom/.cache

#skippy_xd_install

fd_install
xcape_install
kakoune_install
howl_install
uni_network_setup
# remove_packages



sudo chown -R tom:tom /home/tom/.cache



}



post_install_function
sudo dnf install -y preload
$df/setup/dotbot/dotbot/bin/dotbot  -c "$df/setup/dotbot/install.conf.yaml" -d "$df"
. "$HOME/.bashrc"
mkdir -p  $QUICKNOTEFILE
