#!/bin/bash




install_archive_tools  ()   {

sudo dnf install -y zip rar tar unzip unrar p7zip p7zip-full bzip2 gzip

}

install_automation_tools  ()   {

sudo dnf install -y wmctrl xdotool

}

install_build_tools  ()   {

sudo dnf install -y autoconf autogen automake autotools-dev build-essential cmake make gcc rake  pkg-config

}

install_download_tools  ()   {
sudo dnf install -y curl git wget

}



install_prog_langs  ()   {
sudo dnf install -y ruby perl


}

remove_packages ()   {

sudo dnf purge -y activity-log-manager aisleriot gnome-mahjongg gnome-mines gnome-sudoku hplip landscape-client-ui-install overlay-scrollbar overlay-scrollbar-gtk2 overlay-scrollbar-gtk3 remmina rhythmbox shotwell shotwell-common thunderbird unity-scope-manpages unity-scope-openclipart usb-creator-gtk webbrowser-app xdiagnose darktable dillo empathy evolution  polari putty putty-tools samba firefox netsurf-gtk
}



install_gnome-pie  ()   {
sudo dnf install -y  gnome-pie 
}

install_bleachbit  ()   {
sudo dnf install -y  bleachbit
}


install_keepass2()   {
sudo dnf install -y   keepass2 


}



install_emelfm2()   {
sudo dnf install  -y   emelfm2
}






jumpapp_install () {

git clone https://github.com/mkropat/jumpapp.git
cd jumpapp
make rpm
sudo yum localinstall jumpapp*.noarch.rpmgit clone https://
}

fish_install () {
sudo dnf install -y fish
}

conda_install () {
install_download_tools
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
sh Miniconda3-latest-Linux-x86_64.sh -b
export PATH="/home/tom/miniconda3/bin:$PATH"
pip install --upgrade pip
rm Miniconda3-latest-Linux-x86_64.sh
}

go_install () {
install_download_tools
curl https://raw.githubusercontent.com/PursuanceProject/install-go/master/install-go.sh | bash
}





extraterm_install () {
cd ~
install_download_tools
mkdir -p apps
wget https://github.com/sedwards2009/extraterm/releases/download/v0.33.1/extraterm-0.33.1-linux-x64.zip
unzip extraterm-0.33.1-linux-x64.zip -d apps
rm  extraterm-0.33.1-linux-x64.zip
cd ~
}



dotfiles_install () {
cd ~
cd /core
./install
cd~
}

fd_install () {
dnf install -y fd-find

}

xcape_install () {
install_build_tools
install_download_tools
sudo dnf install -y  git gcc make pkgconfig libX11-devel libXtst-devel libXi-devel
	
git clone https://github.com/alols/xcape.git
cd xcape
make
sudo make install
cd ..
rm -rf xcape


}




